trigger: none

variables:
  tag_api: 'api'

stages:
- stage: BuildAndPush
  displayName: Build and push Docker app image manually
  jobs:
  - job: BuildPushJob
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        docker build -t diegeauq/daan_proyecto:$(tag_api) $(Build.SourcesDirectory)/EF-DiegoQuispeR
      displayName: Build app image

    - task: Docker@2
      displayName: Push app image to Docker Hub
      inputs:
        containerRegistry: 'docker-hub'
        repository: 'diegeauq/daan_proyecto'
        command: 'push'
        tags: |
          $(tag_api)

    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: 'docker-hub'

    - script: |
        docker compose -f $(Build.SourcesDirectory)/EF-DiegoQuispeR/docker-compose.yml up -d
      displayName: Start services

    - script: |
        docker compose -f $(Build.SourcesDirectory)/EF-DiegoQuispeR/docker-compose.yml down
      displayName: Stop and clean up






