FROM mcr.microsoft.com/mssql/server:2022-CU12-ubuntu-20.04

ENV ACCEPT_EULA=Y

USER root

# Install sqlcmd
RUN apt-get update && \
	apt-get install -y curl gnupg && \
	curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
	curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list && \
	apt-get update && \
	ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev && \
	echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc

COPY backups/biblioteca_db_bak.bak /var/opt/mssql/backups/biblioteca_db_bak.bak
COPY restore-db.sh /usr/config/restore-db.sh

RUN chmod +x /usr/config/restore-db.sh

USER mssql

CMD ["/bin/bash", "/usr/config/restore-db.sh"]