
services:
  web:
    build: .
    ports:
      - "5000:44374" 
    depends_on:
      - db
    environment:
      ASPNETCORE_URLS: "http://+:44374"
      ConnectionStrings__DefaultConnection: "Server=db;Database=db_biblioteca;User Id=sa;Password=CoolyPassy0!"

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "CoolyPassy0!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./sql_data:/var/opt/mssql/data
      - ./backups:/var/opt/mssql/backups
