version: '3.8'

services:
  web:
    image: diegeauq/daan_proyecto:api
    ports:
      - "5001:44374"
    depends_on:
      - db
    environment:
      ASPNETCORE_URLS: "https://+:44374"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "${HTTPS_CERT_PASSWORD}"
      ConnectionStrings__cn: "Server=db;Database=db_biblioteca;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True"
      JWT_SECRET: "${JWT_SECRET}"
    volumes:
      - "${USERPROFILE}/.aspnet/https:/https:ro"

  db:
    image: diegeauq/daan_proyecto:db
    environment:
      SA_PASSWORD: "${DB_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:

