version: '3.8'

services:
  web:
    build: .
    image: diegeauq/daan_proyecto:latest
    ports:
      - "5000:44374"
    depends_on:
      - db
    environment:
      ASPNETCORE_URLS: "http://+:44374"
      ConnectionStrings__DefaultConnection: "Server=db;Database=dbbteca;User Id=sa;Password=CoolyPassy0!"

  db:
    image: diegeauq/daan_db:latest
    environment:
      SA_PASSWORD: "CoolyPassy0!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:


